from datetime import datetime
from typing import Generator
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Text
from sqlalchemy.orm import declarative_base, sessionmaker, Session

# Database URL - SQLite for backend branch
DATABASE_URL = "sqlite:///./trace_mark.db"

engine = create_engine(
    DATABASE_URL, 
    connect_args={"check_same_thread": False}
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class IssuedDocument(Base):
    """
    Audit log of all fingerprinted PDFs generated by the system.
    """
    __tablename__ = "issued_documents"

    id = Column(Integer, primary_key=True, index=True)
    exam_id = Column(String(32), nullable=False, index=True)
    press_id = Column(String(16), nullable=False, index=True)
    batch_id = Column(String(16), nullable=False)
    center_id = Column(String(16), nullable=False, index=True)
    copy_number = Column(Integer, nullable=False)
    
    sha256_hash = Column(String(64), unique=True, nullable=False, index=True)
    input_path = Column(Text, nullable=False)
    output_path = Column(Text, nullable=False)
    
    payload_bits = Column(Integer, nullable=False)
    pages_encoded = Column(Integer, nullable=False)
    shift_points = Column(Float, nullable=False)
    ssim_score = Column(Float, nullable=False)
    
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

class ForensicScan(Base):
    """
    Audit log of all smartphone photo forensic leak investigations.
    """
    __tablename__ = "forensic_scans"

    id = Column(Integer, primary_key=True, index=True)
    scan_uuid = Column(String(36), unique=True, nullable=False, index=True)
    uploaded_image_path = Column(Text, nullable=False)
    
    # Recovered Provenance Data
    detected_exam_id = Column(String(32), nullable=True)
    detected_press_id = Column(String(16), nullable=True)
    detected_batch_id = Column(String(16), nullable=True)
    detected_center_id = Column(String(16), nullable=True)
    detected_copy_number = Column(Integer, nullable=True)
    
    # Forensic Analytics
    confidence_score = Column(Float, default=0.0, nullable=False)
    bit_error_rate = Column(Float, default=1.0, nullable=False)
    ecc_corrections_made = Column(Integer, default=0, nullable=False)
    status = Column(String(20), default="PENDING", nullable=False)  # SUCCESS, FAILED, UNREADABLE
    
    scanned_at = Column(DateTime, default=datetime.utcnow, nullable=False)

def init_db():
    """Creates database tables if they do not exist."""
    Base.metadata.create_all(bind=engine)

def get_db() -> Generator[Session, None, None]:
    """FastAPI Dependency for database session management."""
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

if __name__ == "__main__":
    init_db()
    print("Database tables initialized successfully in trace_mark.db")