import uuid
from datetime import datetime
from typing import Generator
from sqlalchemy import create_engine, Column, Integer, String, Float, DateTime, Text, ForeignKey, inspect, text
from sqlalchemy.orm import declarative_base, sessionmaker, Session

# Database URL - SQLite for backend branch
DATABASE_URL = "sqlite:///./trace_mark.db"

engine = create_engine(
    DATABASE_URL, 
    connect_args={"check_same_thread": False}
)

SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base = declarative_base()

class User(Base):
    __tablename__ = "users"
    
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    full_name = Column(String(100), nullable=True)
    email = Column(String(120), unique=True, index=True, nullable=True)
    organization_name = Column(String(160), nullable=True)
    press_id = Column(String(64), nullable=True)
    center_code = Column(String(64), nullable=True)
    role = Column(String(32), nullable=False, default="analyst")
    password_hash = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

class UserSession(Base):
    __tablename__ = "user_sessions"
    id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class OTPChallenge(Base):
    __tablename__ = "otp_challenges"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=False)
    code_hash = Column(String(255), nullable=False)
    expires_at = Column(DateTime, nullable=False)
    used_at = Column(DateTime, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

class IssuedDocument(Base):
    """Audit log of all fingerprinted PDFs generated by the system."""
    __tablename__ = "issued_documents"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=True) # Scoped to user
    exam_id = Column(String(32), nullable=False, index=True)
    press_id = Column(String(16), nullable=False, index=True)
    batch_id = Column(String(16), nullable=False)
    center_id = Column(String(16), nullable=False, index=True)
    copy_number = Column(Integer, nullable=False)
    
    sha256_hash = Column(String(64), unique=True, nullable=False, index=True)
    input_path = Column(Text, nullable=False)
    output_path = Column(Text, nullable=False)
    
    payload_bits = Column(Integer, nullable=False)
    pages_encoded = Column(Integer, nullable=False)
    shift_points = Column(Float, nullable=False)
    ssim_score = Column(Float, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

class ForensicScan(Base):
    """Audit log of all smartphone photo forensic leak investigations."""
    __tablename__ = "forensic_scans"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=True) # Scoped to user
    scan_uuid = Column(String(36), unique=True, nullable=False, index=True)
    uploaded_image_path = Column(Text, nullable=False)
    
    # Recovered Provenance Data
    detected_exam_id = Column(String(32), nullable=True)
    detected_press_id = Column(String(16), nullable=True)
    detected_batch_id = Column(String(16), nullable=True)
    detected_center_id = Column(String(16), nullable=True)
    detected_copy_number = Column(Integer, nullable=True)
    
    # Forensic Analytics
    confidence_score = Column(Float, default=0.0, nullable=False)
    bit_error_rate = Column(Float, default=1.0, nullable=False)
    ecc_corrections_made = Column(Integer, default=0, nullable=False)
    status = Column(String(20), default="PENDING", nullable=False)  
    scanned_at = Column(DateTime, default=datetime.utcnow, nullable=False)

class LeakFinding(Base):
    """Tracks active leaks assigned for investigation."""
    __tablename__ = "leak_findings"

    id = Column(Integer, primary_key=True, index=True)
    scan_uuid = Column(String(36), ForeignKey("forensic_scans.scan_uuid"), index=True, nullable=False)
    user_id = Column(Integer, ForeignKey("users.id"), index=True, nullable=False)
    severity = Column(String(20), index=True, nullable=False) # HIGH, CRITICAL, MEDIUM
    source_center = Column(String(50), nullable=False)
    status = Column(String(20), index=True, default="INVESTIGATING")
    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)

def init_db():
    Base.metadata.create_all(bind=engine)
    # Keep existing local SQLite databases compatible after adding profile fields.
    columns = {column["name"] for column in inspect(engine).get_columns("users")}
    additions = {
        "full_name": "VARCHAR(100)",
        "organization_name": "VARCHAR(160)",
        "press_id": "VARCHAR(64)",
        "center_code": "VARCHAR(64)",
        "role": "VARCHAR(32) DEFAULT 'analyst'",
    }
    with engine.begin() as connection:
        for name, definition in additions.items():
            if name not in columns:
                connection.execute(text(f"ALTER TABLE users ADD COLUMN {name} {definition}"))
        connection.execute(text("UPDATE users SET full_name = name WHERE full_name IS NULL"))

def get_db() -> Generator[Session, None, None]:
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

if __name__ == "__main__":
    init_db()
    print("Database tables initialized successfully in trace_mark.db")